
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReduxProvider from "@/app/redux/provider";
import InitUser from "@/app/redux/intUser";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full  antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
              <main className="relative h-screen  bg-slate-950 text-white">
      {/* Animated Background */}
      <div className="absolute inset-0">
        <div className="absolute top-20 left-20 h-72 w-72 rounded-full bg-cyan-500/20 blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-20 h-80 w-80 rounded-full bg-purple-500/20 blur-3xl animate-pulse"></div>
        <div className="absolute top-1/2 left-1/2 h-96 w-96 -translate-x-1/2 -translate-y-1/2 rounded-full bg-blue-500/10 blur-3xl"></div>
      </div>

      {/* Navigation */}
      <header className="relative z-10">
        <nav className="mx-auto flex max-w-7xl items-center justify-between px-8 py-6">
          <h1 className="text-xl font-bold tracking-wider">
            CMS by <span className="text-cyan-400">Mannu</span>
          </h1>

          <ul className="hidden gap-8 md:flex">
            <li>
              <Link
                href="/"
                className="transition hover:text-cyan-400"
              >
                Home
              </Link>
            </li>

            <li>
              <Link
                href="/posts"
                className="transition hover:text-cyan-400"
              >
                Posts
              </Link>
            </li>

            <li>
              <Link
                href="/pages"
                className="transition hover:text-cyan-400"
              >
                Pages
              </Link>
            </li>

            <li>
              <Link
                href="/about"
                className="transition hover:text-cyan-400"
              >
                About Me
              </Link>
            </li>
          </ul>
        </nav>
      </header>
          <InitUser />

          {children}
              </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
